#On /.github/workflows
#hola-mundo.yml
name: hola-mundo 
on:
  push:
    branches: [ "aprendiendo-github-actions" ]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: python ../../hello_world.py #or just python hola_mundo.py
